FROM cgr.dev/chainguard/wolfi-base
LABEL org.opencontainers.image.source https://github.com/uptime-lab/computeblade-agent

# Copy binaries generated by goreleaser
COPY computeblade-agent bladectl /bin

ENTRYPOINT ["/bin/computeblade-agent"]
